/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.Jeka8833.GenomeTests;

import com.Jeka8833.GenomeTests.world.FileSaver;
import com.Jeka8833.GenomeTests.world.World;
import com.Jeka8833.GenomeTests.world.WorldTimeManager;
import org.jetbrains.annotations.NotNull;

import javax.swing.*;
import java.io.IOException;
import java.nio.file.Path;

/**
 * @author Jeka8833
 */
public class ConsoleGUI extends javax.swing.JFrame {

    private WorldTimeManager timeManager;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        logPaneUI = new javax.swing.JTextArea();
        consoleInputUI = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        statusPaneUI = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        logPaneUI.setEditable(false);
        logPaneUI.setColumns(20);
        logPaneUI.setRows(5);
        jScrollPane1.setViewportView(logPaneUI);

        consoleInputUI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.@NotNull KeyEvent evt) {
                consoleInputUIKeyPressed(evt);
            }
        });

        jLabel1.setText("Console logs:");

        statusPaneUI.setEditable(false);
        statusPaneUI.setColumns(20);
        statusPaneUI.setRows(5);
        jScrollPane2.setViewportView(statusPaneUI);

        jLabel2.setText("Status pane:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(consoleInputUI, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(jLabel2))
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(consoleInputUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane2))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consoleInputUIKeyPressed(java.awt.event.@NotNull KeyEvent evt) {//GEN-FIRST:event_consoleInputUIKeyPressed
        if (evt.getKeyCode() == 10) {
            String[] args = consoleInputUI.getText().split(" ");
            if (args.length == 0) return;
            addLog("Command: " + consoleInputUI.getText());
            String command = args[0].toLowerCase();

            switch (command) {
                case "start":
                    if (timeManager.isRun()) {
                        addLog("Error: worlds already started");
                    } else {
                        timeManager.start();
                        addLog("Success");
                    }
                    break;
                case "stop":
                    if (timeManager.isRun()) {
                        timeManager.stop();
                        addLog("Success");
                    } else {
                        addLog("Error: worlds already stopped");
                    }
                    break;
                case "save":
                    try {
                        FileSaver.saveToFile(Path.of("", "saves", System.currentTimeMillis() + ""), timeManager);
                        addLog("Success");
                    } catch (IOException e) {
                        addLog("Error save worlds: " + e);
                    }
                    break;
                case "load":
                    try {
                        setTimeManager(FileSaver.loadFromFile(Path.of(args[1]), WorldTimeManager.class));
                    } catch (IOException | ClassNotFoundException e) {
                        addLog("Error load worlds: " + e);
                    }
                    break;
                case "list":
                    if (timeManager.getWorlds().isEmpty()) {
                        addLog("Worlds not found");
                    } else {
                        addLog("Worlds:");
                        for (World world : timeManager.getWorlds()) {
                            addLog("- " + world.getName() + " " + world.getWidth() + "x" + world.getHeight());
                        }
                    }
                    break;
                case "speed":
                    try {
                        World world = timeManager.getWorld(args[1]);
                        if (world == null) {
                            addLog("World not found");
                        } else {
                            world.setLimitTickPerMinute(Integer.parseInt(args[2]));
                            addLog("Set tick limit: " + world.getLimitTickPerMinute());
                        }
                    } catch (Exception e) {
                        addLog("Fail set speed: " + e);

                    }
                    break;
                case "tick":
                    try {
                        World world = timeManager.getWorld(args[1]);
                        if (world == null) {
                            addLog("World not found");
                        } else {
                            world.tick();
                            addLog("World ticked");
                        }
                    } catch (Exception e) {
                        addLog("Fail set speed: " + e);

                    }
                    break;
                default:
                    addLog("Error command: " + command);
            }

            consoleInputUI.setText("");
        }
    }//GEN-LAST:event_consoleInputUIKeyPressed

    public static @NotNull ConsoleGUI create() {
        var console = new ConsoleGUI();

        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsoleGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        var timer = new Timer(3000, e -> {
            if (console.timeManager != null) {
                var sb = new StringBuilder();

                sb.append("Simulation ").append(console.timeManager.getWorlds().size()).append(" worlds is ")
                        .append(console.timeManager.isRun() ? "Started" : "Stopped").append("\n");

                for (int i = 0; i < console.timeManager.getWorlds().size(); i++) {
                    World world = console.timeManager.getWorlds().get(i);
                    sb.append(world.getName()).append(": TPM: ")
                            .append(world.getAvgTickPerMinute()).append("\n")
                            .append("Tick: ").append(world.getTickCount()).append("\n");
                }

                console.statusPaneUI.setText(sb.toString());
            }
        });
        timer.start();

        java.awt.EventQueue.invokeLater(() -> {
            console.initComponents();
            console.setVisible(true);
        });

        return console;
    }

    public void addLog(String text) {
        logPaneUI.append(text + "\n");
    }

    public void setTimeManager(WorldTimeManager timeManager) {
        this.timeManager = timeManager;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField consoleInputUI;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea logPaneUI;
    private javax.swing.JTextArea statusPaneUI;
    // End of variables declaration//GEN-END:variables
}
